"""renaming friends table

Revision ID: 37c338c19837
Revises: a71810363a53
Create Date: 2022-10-14 16:17:51.205852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37c338c19837'
down_revision = 'a71810363a53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_FriendRequests_id', table_name='FriendRequests')
    op.drop_table('FriendRequests')

    op.create_table(
        'Friends',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('message', sa.Text, default=None),
        sa.Column('sent_at', sa.DateTime(timezone=True),
                  server_default=sa.sql.func.now()),
        sa.Column('accepted_at', sa.DateTime(timezone=True),
                  server_default=sa.sql.func.now()),
        sa.Column('status', sa.Integer, default=1),
        sa.Column('sender_id', sa.Integer, sa.ForeignKey(
            'Users.id'), nullable=False),
        sa.Column('recipient_id', sa.Integer,
                  sa.ForeignKey('Users.id'), nullable=False)

    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FriendRequests',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"FriendRequests_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('message', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=True),
                    sa.Column('sender_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('recipient_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['recipient_id'], ['Users.id'], name='FriendRequests_recipient_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['sender_id'], ['Users.id'], name='FriendRequests_sender_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='FriendRequests_pkey')
                    )
    op.create_index('ix_FriendRequests_id',
                    'FriendRequests', ['id'], unique=False)
    op.drop_table('Friends')
    # ### end Alembic commands ###
