"""friends with proper relationship

Revision ID: 8d35771eae4a
Revises: 7e342b381830
Create Date: 2022-10-12 01:50:16.911909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d35771eae4a'
down_revision = '7e342b381830'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_column('FriendRequests', 'request_id')
    op.add_column('FriendRequests', sa.Column(
        'id', sa.Integer, primary_key=True, index=True))
    op.add_column('FriendRequests', sa.Column('sent_at', sa.DateTime(
        timezone=True), server_default=sa.sql.func.now()))
    op.alter_column('FriendRequests', 'Message',
                    new_column_name='new_col_name')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FriendRequests',
                    sa.Column('request_id', sa.INTEGER(), server_default=sa.text(
                        'nextval(\'"FriendRequests_request_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
                    sa.Column('message', sa.TEXT(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'request_id', name='FriendRequests_pkey')
                    )
    op.create_index('ix_FriendRequests_request_id',
                    'FriendRequests', ['request_id'], unique=False)
    # ### end Alembic commands ###
