"""tweaking accepted_at column

Revision ID: bbe4d3de1ef1
Revises: 37c338c19837
Create Date: 2022-10-15 15:33:24.168048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbe4d3de1ef1'
down_revision = '37c338c19837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('Friends', 'accepted_at', nullable=True,
                    default=None, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Friends', 'accepted_at', server_default=sa.sql.func.now())
    # ### end Alembic commands ###
